workflows: replace references with local actions (#4)

diff --git a/.github/workflows/build_binaries.yaml b/.github/workflows/build_binaries.yaml
--- a/.github/workflows/build_binaries.yaml
+++ b/.github/workflows/build_binaries.yaml
@@ -5,16 +5,88 @@ on: [push, workflow_dispatch]
 permissions:
   contents: write
 
+env:
+  ARTIFACT_NAME: Firmware
+
 jobs:
   build:
-    name: 'QMK Userspace Build'
-    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@2136ded0cdc263e4cc0c2abced3ad4e2222cf1cb
-    with:
-      qmk_repo: qmk/qmk_firmware
-      qmk_ref: 08e5fcfdf44c73fbbc8887b100fccd00006aa02e
+    runs-on: ubuntu-latest
+    container: ghcr.io/qmk/qmk_cli:latest
+    steps:
+      - name: Checkout Userspace
+        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
+        with:
+          token: ${{ github.token }}
+          submodules: recursive
+
+      - name: Checkout QMK Firmware
+        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
+        with:
+          token: ${{ github.token }}
+          path: qmk_firmware
+          repository: 'qmk/qmk_firmware'
+          ref: 08e5fcfdf44c73fbbc8887b100fccd00006aa02e # v0.31.1
+          submodules: recursive
+
+      - name: Install QMK CLI dependencies
+        run: |
+          echo '$PATH'
+          echo $PATH | tr ':' '\n' | sed -e 's/^/ - /g'
+          pip install -r qmk_firmware/requirements.txt
+
+      - name: Configure QMK CLI
+        run: |
+          qmk config userspace_compile.parallel=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
+          qmk config user.qmk_home=$GITHUB_WORKSPACE/qmk_firmware
+          qmk config user.overlay_dir=$GITHUB_WORKSPACE
+
+      - name: Validate userspace
+        run: |
+          qmk userspace-doctor
+
+      - name: Build
+        run: |
+          qmk userspace-compile -e DUMP_CI_METADATA=yes || touch .failed
+          # Generate the step summary markdown
+          ./qmk_firmware/util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
+          # Truncate to a maximum of 1MB to deal with GitHub workflow limit
+          truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
+          # Exit with failure if the compilation stage failed
+          [ ! -f .failed ] || exit 1
+
+      - name: Upload binaries
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+        if: always() && !cancelled()
+        continue-on-error: true
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+          path: |
+            *.bin
+            *.hex
+            *.uf2
 
   publish:
-    name: 'QMK Userspace Publish'
-    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@2136ded0cdc263e4cc0c2abced3ad4e2222cf1cb
-    if: always() && !cancelled()
+    runs-on: ubuntu-latest
+    if: github.ref_name == 'main' && !cancelled()
     needs: build
+    steps:
+      - name: Download binaries
+        if: always() && !cancelled()
+        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+
+      - name: Generate Release
+        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
+        if: always() && !cancelled()
+        with:
+          token: ${{ github.token }}
+          name: QMK Firmware
+          tag_name: ${{ github.sha }}
+          fail_on_unmatched_files: false
+          draft: false
+          prerelease: false
+          files: |
+            **/*.hex
+            **/*.bin
+            **/*.uf2
